# NumPy Indexing and Selection
如何將選定在數列中的特定元素或特定群組

In [1]:
import numpy as np

In [8]:
array = np.arange(11)

In [9]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 
## 向量 (1-d array) 的索引

選單個值：

In [12]:
array[8]

8

選定一個範圍：

In [13]:
array[1:5]

array([1, 2, 3, 4])

In [14]:
array[0:5]

array([0, 1, 2, 3, 4])

### 
## 廣播 Broadcast
廣播：給定索引範圍一個值，Numpy 不同於普通的 Python list，因為它們能夠廣播：

In [17]:
array[0:5]=100

array

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [19]:
array = np.arange(0,11)

array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
slice_of_arr = array[0:6]

slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [25]:
slice_of_arr[:]=99

slice_of_arr

array([99, 99, 99, 99, 99, 99])

**注意**：原始數列也會被改變！

In [26]:
array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

可以利用 `.copy()` 避免此問題：

In [28]:
arr_copy = array.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### 
## 矩陣 (Matrices) 的索引 2-d array
### 公式：`arr_2d [row] [col]` 或 `arr_2d [row, col]`

ex.

In [29]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

**row 索引 :**

In [30]:
arr_2d[1]

array([20, 25, 30])

**指定元素索引，先 row 後 col:**

In [31]:
arr_2d[1][0] # arr_2d[1][0] = arr_2d[1,0]

20

In [32]:
arr_2d[1,0] # arr_2d[1][0] = arr_2d[1,0]

20

**切片 Slice :**

In [34]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [37]:
# 最前一行取到第2行，第1列取到最後一列

arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [38]:
arr_2d[2]

array([35, 40, 45])

In [39]:
arr_2d[2, :]

array([35, 40, 45])

### 
## 特殊索引方法

In [41]:
arr2d = np.zeros((10,10))

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [42]:
arr_length = arr2d.shape[1]

In [43]:
for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

**只挑選特定 row :**

In [44]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [45]:
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

### 
## 篩選 Selection

In [46]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [49]:
bool_arr = arr>4

In [50]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [51]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [52]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])