# Numpy
**- NumPy 是 Python 的線性代數庫，它對 Python 數據科學如此重要的原因是 PyData 生態系統中的幾乎所有庫都依賴 NumPy 作為其主要構建塊之一。**

In [1]:
import numpy as np

### 

## Numpy Arrays
NumPy Arrays 是我們在整個課程中使用 Numpy 的主要方式。 Numpy Arrays 基本上有兩種形式：`Vectors(向量)`和 `Matrices(矩陣)`。Vectors 是嚴格的 1-d arrays(一維數列)，Matrices 是 2-d (二維)的（但你應該注意 Matrices 仍然只能有一行或一列）。

### 

### 我們可以直接將 list 轉變成 array : `np.array( )`

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 

### `np.arange( 最小值, 最大值, 間隔 )`：返回給定間隔內均勻間隔的值

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### 

### `np.zeros( 行數(rows) , 欄數(columns) )`   和
### `np.ones( 行數(rows) , 欄數(columns) )`：
**- 產生為 0 / 1 的矩陣**

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 
### `np.linspace( 開始值, 終點值, 個數 )`：返回一個間隔相同的數列

In [12]:
# 建立一個從 0 開始 10  結束，間隔相同，由 3 個數組成的數列

np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [13]:
# 建立一個從 0 開始 10  結束，間隔相同，由 50 個數組成的數列


np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### 
### `np.eye()`  : 成立一個對角線為 1 的數列

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### 
## Random
### `np.random.rand( 行數, 欄數 )` :  創建一個數值在0-1之間的隨機數列

In [16]:
np.random.rand(2)

array([0.37068605, 0.82507109])

In [17]:
np.random.rand(5,5)

array([[0.83022109, 0.1258671 , 0.57198347, 0.64030811, 0.704024  ],
       [0.05532246, 0.00793491, 0.73982289, 0.21675785, 0.51298532],
       [0.94254147, 0.02404374, 0.22972711, 0.88972819, 0.31317677],
       [0.88015216, 0.3902288 , 0.03512371, 0.89281001, 0.07665195],
       [0.75619847, 0.50715007, 0.81289401, 0.42736587, 0.47109162]])

### `np.random.randn( 行數, 欄數 )` : 創建一個隨機數列，沒有限定範圍                                            

In [18]:
np.random.randn(2)

array([-1.12600339, -0.2418107 ])

In [22]:
np.random.randn(5,5)

array([[ 1.59935414, -1.74796303,  0.42654168, -1.26902228, -0.30096008],
       [ 0.58788073, -1.45215726,  0.34138133,  0.02932696,  0.9818526 ],
       [ 0.53397827,  0.15714169, -1.29777145,  0.69042357, -1.6261102 ],
       [ 0.19808337,  1.06931526, -1.63792228, -1.10595569, -0.05066495],
       [-0.44596147, -0.23231308, -0.65577518,  0.06802946,  0.56349556]])

### `np.random.randint( low, high, size )` : 產生一個範圍在 low-high 之間隨機數列，size 控制數列數量

In [23]:
np.random.randint(1,100)

68

In [53]:
np.random.randint(4,size=100)

array([2, 1, 3, 0, 1, 0, 0, 1, 3, 2, 3, 0, 1, 3, 1, 3, 3, 1, 2, 2, 0, 2,
       1, 1, 1, 0, 0, 2, 3, 3, 1, 3, 2, 3, 0, 2, 2, 0, 1, 0, 3, 2, 3, 3,
       3, 0, 0, 3, 3, 3, 3, 2, 2, 0, 1, 3, 0, 1, 1, 3, 0, 0, 1, 3, 1, 2,
       1, 2, 2, 0, 3, 2, 1, 1, 1, 0, 3, 3, 1, 3, 1, 2, 0, 0, 2, 3, 3, 0,
       1, 2, 1, 2, 3, 0, 1, 3, 2, 2, 2, 0])

In [27]:
# 產生一個 10 個數字組成的數列，每個數字大小為 1-100 之間隨機

np.random.randint(1,100,10)

array([69, 22, 32, 91, 16, 38, 27, 64, 38, 82])

### 
## Arrays 屬性和方法

In [31]:
array = np.arange(25)
random_array = np.random.randint(0,50,10)

In [32]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
random_array

array([ 7,  7, 38,  4, 18, 47, 16, 13,  7, 36])

### `.reshape( 行數, 欄數 )`：將原來的data變成新的型態

In [34]:
array.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
random_array

array([ 7,  7, 38,  4, 18, 47, 16, 13,  7, 36])

### `.max( )` : 找出數列中最大數值

In [40]:
random_array.max()

47

### `.argmax( )` : 找出數列中最大數值的位置

In [41]:
random_array.argmax()

5

### `.min( )` : 找出數列中最小數值

In [42]:
random_array.min()

4

### `.argmin( )` : 找出數列中最小數值位置

In [43]:
random_array.argmin()

3

### `.shape` : 查看數列的維度

In [44]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
array.shape

(25,)

**( x, y ) : x 可以理解為第一個[ ]內有多少[ ] ( 代表維度 )，y 是每個[ ]裡有多少個數值 :**

In [49]:
array.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [48]:
array.reshape(1,25).shape

(1, 25)

In [50]:
array.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [51]:
array.reshape(25,1).shape

(25, 1)

### `.sum( )` : 計算數列的加總

In [54]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [55]:
array.sum()

300

**計算所有欄的加總 `.sum(axis=0)`**

In [60]:
array = array.reshape(5,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [61]:
array.sum(axis=0)

array([50, 55, 60, 65, 70])

### `.std( )` : 計算數列的標準差

In [56]:
array.std()

7.211102550927978

### 
### `.dtype` : 查看數值 data type

In [52]:
array.dtype

dtype('int64')